### ISSUE TITLE
fis3 release -w dev这条命令太多坑了

### ISSUE THREAD

**Issue by cheng7692019** [feix760/Chrome_12306#6]
先是operation not permitted, scandir C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\Content.IE5
删掉了Content.IE5
然后又是resource busy or locked open C:\WINDOWS\system32\config\BBI.LOG1
win10上怎么这么难运行fis3

**Comment by allanruin** [comment]
==其实不只是win10，我在ubuntu下运行也是[二哈]

    gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/allan/.node-gyp/6.9.4"

==好吧，我看了下，这个其实是v8-debug那边的祸。

    Seems there are issues with node-inspector and any version of Node >= 6.4.x. See this thread.

而我用的是v6.9.4，Orz

**Comment by feix760** [comment]
已换用webpack

**Comment by yintao** [comment]
C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\Content.IE5
这个文件没有怎么处理呀？
